# VO detector parameters

detector_intensity_threshold:
    param_name: intensity_threshold
    base_namespace: visual_odometry/vo_node/detector
    lower_limit: 20
    upper_limit: 200
detector_max_num_points:
    param_name: max_num_points
    base_namespace: visual_odometry/vo_node/detector
    lower_limit: 25
    upper_limit: 1000