# VO detector parameters

detector_intensity_threshold:
    param_name: intensity_threshold
    base_namespace: visual_odometry/vo_node/detector
    lower_limit: 0
    upper_limit: 255
detector_max_num_points:
    param_name: max_num_points
    base_namespace: visual_odometry/vo_node/detector
    lower_limit: 1
    upper_limit: 1000