# VO LK tracker parameters
tracker_max_iters:
    param_name: max_iters
    base_namespace: visual_odometry/vo_node/tracker
    lower_limit: 10
    upper_limit: 250
tracker_log_min_eps:
    param_name: log_min_eps
    base_namespace: visual_odometry/vo_node/tracker
    lower_limit: -3
    upper_limit: 0
tracker_pyramid_level:
    param_name: pyramid_level
    base_namespace: visual_odometry/vo_node/tracker
    lower_limit: 0
    upper_limit: 5
tracker_window_dim:
    param_name: window_dim
    base_namespace: visual_odometry/vo_node/tracker
    lower_limit: 5
    upper_limit: 50
tracker_flow_error:
    param_name: flow_error_threshold
    base_namespace: visual_odometry/vo_node/tracker
    lower_limit: 0
    upper_limit: 10.0
tracker_log_flow_eigen_threshold:
    param_name: log_flow_eigenvalue_threshold
    base_namespace: visual_odometry/vo_node/tracker
    lower_limit: -6
    upper_limit: -1